# docker-compose 버젼
version: "3.7"

# 컨테이너 목록
services:
  # 컨테이너 이름 변수처럼 직접 고르면 된다.
  db:
    # 컨테이너에 사용할 이미지
    image: mysql:latest
    # 포트 연결 설정
    ports:
      - 3306:3306
    # 컨테이너 실행시에 환경변수 사용
    environment:
      MYSQL_ROOT_PASSWORD: XXXX
      MYSQL_DATABASE: XXXX
    # 재시작하는 조건
    restart: on-failure
    # 컨테이너에 연결할 볼륨 연결
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    # 네트워크 설정
    networks:
      default:
        ipv4_address: 172.16.2.2

  server:
    # 컨테이너에 사용할 Dockerfile이 있는 경로, image 대신에 쓰면, 없는 경우 이미지를 자동으로 빌드하고 컨테이너를 생성한다.
    build: .
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    # 기본적으로 써있는 CMD나 ENTRYPOINT에 덮어쓸 내용
    # entrypoint: "npm run start"
    networks:
      default:
        ipv4_address: 172.16.2.3

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24